export type CatalogFormule = {
  id: string;
  label: string;
  description: string;
  type: "par_personne" | "fixe";
  prixAdulte?: number;
  prixEnfant?: number; // enfants 5-12 ans sauf indication
  ageEnfant?: string;
  prixFixe?: number;
  noteFixe?: string; // ex: "par chambre / par nuit"
};

export type CatalogSite = {
  id: string;
  nom: string;
  emoji: string;
  couleur: string;
  formules: CatalogFormule[];
};

export const catalog: CatalogSite[] = [
  {
    id: "hougeif",
    nom: "Hougeif",
    emoji: "🏖️",
    couleur: "#408398",
    formules: [
      {
        id: "hougeif-nuitee",
        label: "Nuitée — Package complet",
        description: "Guide touristique / Transport voiture / 1 dîner / 2 déjeuners / 1 petit-déjeuner · min 6 pers.",
        type: "par_personne",
        prixAdulte: 27000,
        prixEnfant: 23000,
        ageEnfant: "5 à 10 ans",
      },
      {
        id: "hougeif-f1",
        label: "Formule 1",
        description: "Dîner, Petit-déjeuner, Déjeuner",
        type: "par_personne",
        prixAdulte: 10000,
        prixEnfant: 6500,
        ageEnfant: "5 à 10 ans",
      },
      {
        id: "hougeif-f2",
        label: "Formule 2",
        description: "Dîner, Petit-déjeuner",
        type: "par_personne",
        prixAdulte: 7500,
        prixEnfant: 4500,
        ageEnfant: "5 à 10 ans",
      },
      {
        id: "hougeif-journee",
        label: "Journée uniquement",
        description: "Avec déjeuner",
        type: "par_personne",
        prixAdulte: 3000,
        prixEnfant: 2000,
        ageEnfant: "5 à 10 ans",
      },
    ],
  },
  {
    id: "loubatanleh",
    nom: "Loubatanleh",
    emoji: "🌿",
    couleur: "#059669",
    formules: [
      {
        id: "loub-mabla-double",
        label: "Chambre Mabla — Double",
        description: "70 m² · jusqu'à 6 pers. · Pdj + Dîner inclus · -10% 2ème nuit",
        type: "fixe",
        prixFixe: 44000,
        noteFixe: "par chambre / par nuit",
      },
      {
        id: "loub-mabla-famille",
        label: "Chambre Mabla — Famille",
        description: "70 m² · jusqu'à 6 pers. · 2 adultes + 2 enfants · Pdj + Dîner inclus",
        type: "fixe",
        prixFixe: 65000,
        noteFixe: "par chambre / par nuit",
      },
      {
        id: "loub-arrey-double",
        label: "Chambre Arrey — Double",
        description: "55 m² · jusqu'à 6 pers. · Pdj + Dîner inclus · -10% 2ème nuit",
        type: "fixe",
        prixFixe: 40000,
        noteFixe: "par chambre / par nuit",
      },
      {
        id: "loub-arrey-famille",
        label: "Chambre Arrey — Famille",
        description: "55 m² · jusqu'à 6 pers. · 2 adultes + 2 enfants · Pdj + Dîner inclus",
        type: "fixe",
        prixFixe: 55000,
        noteFixe: "par chambre / par nuit",
      },
      {
        id: "loub-goda-simple",
        label: "Chambre Goda — Simple",
        description: "35 m² · jusqu'à 3 pers. · Pdj + Dîner inclus",
        type: "fixe",
        prixFixe: 20000,
        noteFixe: "par chambre / par nuit",
      },
      {
        id: "loub-goda-double",
        label: "Chambre Goda — Double",
        description: "35 m² · jusqu'à 3 pers. · Pdj + Dîner inclus",
        type: "fixe",
        prixFixe: 34000,
        noteFixe: "par chambre / par nuit",
      },
      {
        id: "loub-ripta-double",
        label: "Chambre Ripta — Double",
        description: "45 m² · jusqu'à 5 pers. · Pdj + Dîner inclus · -10% 2ème nuit",
        type: "fixe",
        prixFixe: 40000,
        noteFixe: "par chambre / par nuit",
      },
      {
        id: "loub-ripta-famille",
        label: "Chambre Ripta — Famille",
        description: "45 m² · jusqu'à 5 pers. · 2 adultes + 2 enfants · Pdj + Dîner inclus",
        type: "fixe",
        prixFixe: 55000,
        noteFixe: "par chambre / par nuit",
      },
      {
        id: "loub-belle-etoile",
        label: "Nuitée à la Belle Étoile",
        description: "Lit simple 90×190 · SDB partagée · Pdj + Dîner inclus · max 10 pers.",
        type: "par_personne",
        prixAdulte: 8000,
        prixEnfant: 4000,
        ageEnfant: "moins de 12 ans",
      },
      {
        id: "loub-adulte-supp",
        label: "Adulte supplémentaire",
        description: "Par adulte supplémentaire dans la chambre",
        type: "fixe",
        prixFixe: 10000,
        noteFixe: "par personne / par nuit",
      },
      {
        id: "loub-enfant-supp",
        label: "Enfant supplémentaire",
        description: "4 à 12 ans · Gratuit pour 0 à 3 ans",
        type: "fixe",
        prixFixe: 6000,
        noteFixe: "par enfant / par nuit",
      },
    ],
  },
  {
    id: "sables-blancs",
    nom: "Sables Blancs",
    emoji: "🏄",
    couleur: "#25D366",
    formules: [
      {
        id: "sb-paillote-f1",
        label: "Paillote — Formule 1",
        description: "Dîner, Petit-déjeuner",
        type: "par_personne",
        prixAdulte: 11000,
        prixEnfant: 6500,
        ageEnfant: "5 à 10 ans",
      },
      {
        id: "sb-paillote-f2",
        label: "Paillote — Formule 2",
        description: "Dîner, Petit-déjeuner, Déjeuner",
        type: "par_personne",
        prixAdulte: 13000,
        prixEnfant: 8500,
        ageEnfant: "5 à 10 ans",
      },
      {
        id: "sb-paillote-f3",
        label: "Paillote — Formule 3",
        description: "Déjeuner, Dîner, Petit-déjeuner et Déjeuner (tout inclus)",
        type: "par_personne",
        prixAdulte: 16000,
        prixEnfant: 10500,
        ageEnfant: "5 à 10 ans",
      },
      {
        id: "sb-hotel-familiale",
        label: "Hôtel — Chambre Familiale",
        description: "4 personnes · 1 grand lit + 2 petits lits · Petit-déjeuner inclus",
        type: "fixe",
        prixFixe: 34500,
        noteFixe: "par chambre / par nuit",
      },
      {
        id: "sb-hotel-double",
        label: "Hôtel — Chambre Double",
        description: "2 personnes · 1 grand lit + salon + frigo · Petit-déjeuner inclus",
        type: "fixe",
        prixFixe: 25000,
        noteFixe: "par chambre / par nuit",
      },
      {
        id: "sb-journee-bateau",
        label: "Excursion Journée en bateau",
        description: "Transport bateau / 1 déjeuner / Paillote · Snorkeling & détente · min 10 pers.",
        type: "par_personne",
        prixAdulte: 10500,
        prixEnfant: 8000,
        ageEnfant: "5 à 10 ans",
      },
      {
        id: "sb-nuitee-bateau",
        label: "Excursion Nuitée en bateau",
        description: "Transport bateau / 2 déjeuners / 1 dîner / 1 petit-déjeuner / Hébergement toukoul · min 10 pers.",
        type: "par_personne",
        prixAdulte: 25000,
        prixEnfant: 19500,
        ageEnfant: "5 à 10 ans",
      },
      {
        id: "sb-repas",
        label: "Repas",
        description: "Par repas, par personne",
        type: "par_personne",
        prixAdulte: 4000,
        prixEnfant: 2000,
        ageEnfant: "5 à 10 ans",
      },
    ],
  },
  {
    id: "ditilou",
    nom: "Ditilou",
    emoji: "🦅",
    couleur: "#7c3aed",
    formules: [
      {
        id: "dit-f1",
        label: "Formule 1",
        description: "Dîner, Petit-déjeuner",
        type: "par_personne",
        prixAdulte: 8000,
        prixEnfant: 6000,
        ageEnfant: "5 à 10 ans",
      },
      {
        id: "dit-f2",
        label: "Formule 2",
        description: "Dîner, Petit-déjeuner, Déjeuner",
        type: "par_personne",
        prixAdulte: 10000,
        prixEnfant: 8000,
        ageEnfant: "5 à 10 ans",
      },
      {
        id: "dit-f3",
        label: "Formule 3",
        description: "Déjeuner, Dîner, Petit-déjeuner et Déjeuner (tout inclus)",
        type: "par_personne",
        prixAdulte: 12000,
        prixEnfant: 10000,
        ageEnfant: "5 à 10 ans",
      },
      {
        id: "dit-journee",
        label: "Journée uniquement",
        description: "Avec déjeuner",
        type: "par_personne",
        prixAdulte: 3000,
        prixEnfant: 2000,
        ageEnfant: "5 à 10 ans",
      },
    ],
  },
  {
    id: "godoria",
    nom: "Godoria",
    emoji: "🌴",
    couleur: "#0891b2",
    formules: [
      {
        id: "god-f1",
        label: "Formule 1",
        description: "Dîner, Petit-déjeuner, Repas du midi",
        type: "par_personne",
        prixAdulte: 12000,
        prixEnfant: 8000,
        ageEnfant: "5 à 10 ans",
      },
      {
        id: "god-f2",
        label: "Formule 2",
        description: "Dîner, Petit-déjeuner (sans repas du midi)",
        type: "par_personne",
        prixAdulte: 7500,
        prixEnfant: 4500,
        ageEnfant: "5 à 10 ans",
      },
      {
        id: "god-journee",
        label: "Journée uniquement",
        description: "Avec déjeuner",
        type: "par_personne",
        prixAdulte: 4000,
        prixEnfant: 3000,
        ageEnfant: "5 à 10 ans",
      },
      {
        id: "god-mangrove",
        label: "Visite Mangrove",
        description: "Visite du site des mangroves · faune et flore · pêche sportive",
        type: "par_personne",
        prixAdulte: 2000,
        prixEnfant: 1000,
        ageEnfant: "5 à 10 ans",
      },
    ],
  },
  {
    id: "lac-abbe",
    nom: "Lac Abbé",
    emoji: "🌋",
    couleur: "#b45309",
    formules: [
      {
        id: "labbe-nuitee",
        label: "Nuitée — Package complet",
        description: "Guide touristique / Transport voiture / 1 dîner / 2 déjeuners / 1 petit-déjeuner · min 6 pers.",
        type: "par_personne",
        prixAdulte: 27000,
        prixEnfant: 23000,
        ageEnfant: "5 à 10 ans",
      },
    ],
  },
  {
    id: "bankoualeh",
    nom: "Bankoualeh",
    emoji: "🌿",
    couleur: "#15803d",
    formules: [
      {
        id: "bank-nuitee",
        label: "Nuitée — Package complet",
        description: "Guide touristique / Transport voiture / 1 dîner / 2 déjeuners / 1 petit-déjeuner · min 6 pers.",
        type: "par_personne",
        prixAdulte: 27000,
        prixEnfant: 23000,
        ageEnfant: "5 à 10 ans",
      },
      {
        id: "bank-f1",
        label: "Formule 1",
        description: "Dîner, Petit-déjeuner",
        type: "par_personne",
        prixAdulte: 8000,
        prixEnfant: 6000,
        ageEnfant: "5 à 10 ans",
      },
      {
        id: "bank-f2",
        label: "Formule 2",
        description: "Dîner, Petit-déjeuner, Déjeuner",
        type: "par_personne",
        prixAdulte: 10000,
        prixEnfant: 8000,
        ageEnfant: "5 à 10 ans",
      },
      {
        id: "bank-f3",
        label: "Formule 3",
        description: "Déjeuner, Dîner, Petit-déjeuner et Déjeuner (tout inclus)",
        type: "par_personne",
        prixAdulte: 12000,
        prixEnfant: 10000,
        ageEnfant: "5 à 10 ans",
      },
      {
        id: "bank-journee",
        label: "Journée uniquement",
        description: "Avec déjeuner",
        type: "par_personne",
        prixAdulte: 3000,
        prixEnfant: 2000,
        ageEnfant: "5 à 10 ans",
      },
    ],
  },
  {
    id: "foret-du-day",
    nom: "Forêt du Day",
    emoji: "🌲",
    couleur: "#166534",
    formules: [
      {
        id: "day-nuitee",
        label: "Nuitée — Package complet",
        description: "Guide touristique / Transport voiture / 2 déjeuners / 1 dîner / 1 petit-déjeuner · Hébergement camping · min 6 pers.",
        type: "par_personne",
        prixAdulte: 27000,
        prixEnfant: 23000,
        ageEnfant: "5 à 10 ans",
      },
      {
        id: "day-f1",
        label: "Formule 1",
        description: "Dîner, Petit-déjeuner",
        type: "par_personne",
        prixAdulte: 8000,
        prixEnfant: 6000,
        ageEnfant: "5 à 10 ans",
      },
      {
        id: "day-f2",
        label: "Formule 2",
        description: "Dîner, Petit-déjeuner, Déjeuner",
        type: "par_personne",
        prixAdulte: 10000,
        prixEnfant: 8000,
        ageEnfant: "5 à 10 ans",
      },
      {
        id: "day-f3",
        label: "Formule 3",
        description: "Déjeuner, Dîner, Petit-déjeuner et Déjeuner (tout inclus)",
        type: "par_personne",
        prixAdulte: 12000,
        prixEnfant: 10000,
        ageEnfant: "5 à 10 ans",
      },
      {
        id: "day-journee",
        label: "Journée uniquement",
        description: "Avec déjeuner",
        type: "par_personne",
        prixAdulte: 3000,
        prixEnfant: 2000,
        ageEnfant: "5 à 10 ans",
      },
    ],
  },
  {
    id: "transport",
    nom: "Transport",
    emoji: "🚗",
    couleur: "#64748b",
    formules: [
      {
        id: "trans-voiture-jour",
        label: "Voiture — Par jour",
        description: "Location véhicule avec chauffeur, journée complète",
        type: "fixe",
        prixFixe: 35000,
        noteFixe: "par jour",
      },
      {
        id: "trans-voiture-lac-assal",
        label: "Voiture — Lac Assal (journée)",
        description: "Aller-retour Lac Assal depuis Djibouti-Ville",
        type: "fixe",
        prixFixe: 45000,
        noteFixe: "par véhicule",
      },
      {
        id: "trans-bateau-moucha-10-nuit",
        label: "Bateau Îles Moucha — 10 places (nuitée)",
        description: "Bateau 10 places · Îles Moucha · avec nuitée",
        type: "fixe",
        prixFixe: 40000,
        noteFixe: "par bateau",
      },
      {
        id: "trans-bateau-moucha-10-jour",
        label: "Bateau Îles Moucha — 10 places (journée)",
        description: "Bateau 10 places · Îles Moucha · journée",
        type: "fixe",
        prixFixe: 30000,
        noteFixe: "par bateau",
      },
      {
        id: "trans-bateau-moucha-6-jour",
        label: "Bateau Sable Moucha — 2 à 6 places (journée)",
        description: "Petit bateau 2-6 places · Sable Moucha · journée",
        type: "fixe",
        prixFixe: 25000,
        noteFixe: "par bateau",
      },
      {
        id: "trans-bateau-moucha-6-nuit",
        label: "Bateau Sable Moucha — 2 à 6 places (nuitée)",
        description: "Petit bateau 2-6 places · Sable Moucha · avec nuitée",
        type: "fixe",
        prixFixe: 35000,
        noteFixe: "par bateau",
      },
      {
        id: "trans-bateau-sb-10-jour",
        label: "Bateau Sables Blancs — 10 places (journée)",
        description: "Grand bateau 10 places · Sables Blancs · journée",
        type: "fixe",
        prixFixe: 60000,
        noteFixe: "par bateau",
      },
      {
        id: "trans-bateau-sb-10-nuit",
        label: "Bateau Sables Blancs — 10 places (nuitée)",
        description: "Grand bateau 10 places · Sables Blancs · avec nuitée",
        type: "fixe",
        prixFixe: 80000,
        noteFixe: "par bateau",
      },
      {
        id: "trans-bateau-sb-6-jour",
        label: "Bateau Sables Blancs — 2 à 6 places (journée)",
        description: "Petit bateau 2-6 places · Sables Blancs · journée",
        type: "fixe",
        prixFixe: 55000,
        noteFixe: "par bateau",
      },
      {
        id: "trans-bateau-sb-6-nuit",
        label: "Bateau Sables Blancs — 2 à 6 places (nuitée)",
        description: "Petit bateau 2-6 places · Sables Blancs · avec nuitée",
        type: "fixe",
        prixFixe: 70000,
        noteFixe: "par bateau",
      },
    ],
  },
];
